name: Generate Release Notes
inputs:
  rng_version:
    description: "Release Notes Generator version"
    required: true
  create_release:
    description: "Whether to create a GitHub Release"
    required: false
    default: "false"
  tag_name:
    description: "The name of the tag for the release"
    required: false

outputs:
  changelog:
    description: "Generated changelog content"
    value: ${{ steps.changelog.outputs.FINAL_CHANGELOG }}
  is_empty:
    description: "True if changelog is empty"
    value: ${{ steps.changelog.outputs.IS_EMPTY }}

runs:
  using: composite
  steps:
    - name: Install Release Notes Generator
      uses: Greewil/release-notes-generator@gha/install/v1
      with:
        rng_version: ${{ inputs.rng_version }}

    - name: generate release notes
      id: changelog
      shell: bash
      run: |
        gen-release-notes -i . -lt -f changelog.md
        
        if [ -s "changelog.md" ]; then
          CHANGELOG=$(cat changelog.md)
          echo "IS_EMPTY=false" >> "$GITHUB_OUTPUT"
        else
          CHANGELOG=''
          echo "IS_EMPTY=true" >> "$GITHUB_OUTPUT"
        fi
        
        echo "FINAL_CHANGELOG<<EOF" >> "$GITHUB_OUTPUT"
        echo "$CHANGELOG" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"

    - name: Create Release
      if: inputs.create_release == 'true' && steps.changelog.outputs.IS_EMPTY == 'false'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        tag_name: ${{ inputs.tag_name || github.ref_name }}
        release_name: ${{ inputs.tag_name || github.ref_name }}
        body: ${{ steps.changelog.outputs.FINAL_CHANGELOG }}
        draft: false
        prerelease: false