name: Install release-notes-generator
description: Install RNG

inputs:
  rng_version:
    description: "Release Notes Generator version (e.g., v1.0.3 or 1.0.3)"
    required: true

runs:
  using: composite
  steps:
    - name: Download RNG
      shell: bash
      run: |
        VERSION="${{ inputs.rng_version }}"
        if [[ $VERSION != v* ]]; then VERSION="v$VERSION"; fi
        curl -f -L -o installer.sh \
          "https://raw.githubusercontent.com/Greewil/release-notes-generator/${VERSION}/installer.sh"
        curl -f -L -o gen_release_notes.sh \
          "https://raw.githubusercontent.com/Greewil/release-notes-generator/${VERSION}/gen_release_notes.sh"
        chmod +x installer.sh
        chmod +x gen_release_notes.sh

    - name: Install RNG
      shell: bash
      run: sudo ./installer.sh -d

    - name: Verify RNG installation
      shell: bash
      run: |
        gen-release-notes -v